server:
  port: 8081

logging:
  level:
    "liquibase" : info

spring:

  datasource:
    url: jdbc:postgresql://localhost:5434/citylist
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem