server:
  port: 8081

logging:
  level:
    "liquibase" : info

spring:

  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5434}/${DB_DATABASE:citylist}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
